spring:
  application:
    name: A #待定
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**  #页面不加载缓存，修改即时生效
  freemarker:
    cache: false

server:
  port: 7003 #项目的端口号
  servlet:
    context-path: /server7000  #配置项目的contextPath

eureka:
  instance:
    appname: server7000appname
    hostname: localhost
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7001/${server.servlet.context-path}/eureka/,http://${eureka.instance.hostname}:7002/${server.servlet.context-path}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0



